import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "./components/Sidebar";
import { ShurikenUIProvider } from "@shuriken-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const navData = [
  {
    title: "Dashboard",
    icon: "ph:gauge-duotone",
    href: "/dashboard",
    //type:link | modal ,
    type: "modal",
    children: [],
  },
  {
    title: "Accounting",
    icon: "ph:grid-four-duotone",
    children: [
      {
        title: "Invoices",
        icon: "ph:grid-four-duotone",
        href: "/accounting/invoices",
        type: "link",
      },
      {
        title: "Expenses",
        href: "/accounting/expenses",
        type: "link",
      },
      {
        title: "Reports",
        href: "/accounting/reports",
        type: "link",
      },
    ],
  },
  {
    title: "Business",
    icon: "ph:briefcase-duotone",
    children: [
      {
        title: "Customers",
        icon: "ph:briefcase-duotone",
        href: "/business/customers",
        type: "link",
      },
      {
        title: "Projects",
        icon: "ph:briefcase-duotone",
        href: "/business/projects",
        type: "link",
      },
      {
        title: "Tasks",
        icon: "ph:briefcase-duotone",
        href: "/business/tasks",
        type: "link",
      },
    ],
  },
  {
    title: "Misc",
    icon: "ph:notification-duotone",
    href: "/misc",
    type: "link",
  },
  {
    title: "Documentation",
    icon: "ph:sticker-duotone",
    children: [
      {
        title: "Getting Started",
        href: "/documentation/getting-started",
        type: "link",
      },
      {
        title: "Components",
        icon: "ph:sticker-duotone",
        children: [
          {
            title: "Button",
            href: "/documentation/components/button",
            type: "link",
          },
          {
            title: "Input",
            href: "/documentation/components/input",
            type: "link",
          },
          {
            title: "CollapseableNav",
            href: "/documentation/components/collapseable-nav",
            type: "link",
          },
          {
            title: "nest",
            icon: "ph:sticker-duotone",
            children: [
              {
                title: "nest",
                icon: "ph:sticker-duotone",
                href: "/documentation/components/nest",
                type: "link",
              },
              {
                title: "nest",
                href: "/documentation/components/nest",
                type: "link",
              },
            ],
          },
        ],
      },
      {
        title: "API Reference",
        href: "/documentation/api-reference",
        type: "link",
      },
    ],
  },
];
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ShurikenUIProvider>
          <div className="flex h-screen w-screen">
            <Sidebar navData={navData} />
            <div className="flex-1 flex-shrink-0 p-8">{children}</div>
          </div>
        </ShurikenUIProvider>
      </body>
    </html>
  );
}
